services:
  db:
    image: postgres:16-alpine
    container_name: tp2_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: tp2
      POSTGRES_PASSWORD: tp2pass
      POSTGRES_DB: tp2_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tp2 -d tp2_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
